## <center>Experint-1</center>






#### <center>NUMPY OPERATIONS
</center>






### Aim:

To study and practice various NumPy operations, including array creation, attributes, indexing, slicing, broadcasting,
arithmetic, statistical operations, concatenation, reshaping, sorting, and splitting using a case study.
<br>


<b>Case Study</b>: A supermarket store manager wants to analyze product sales over 4 weeks in January from their three branches (branch A,
B, and c). Using NumPy, extract meaningful insights from the raw sales data.



**Step 1:** Install and import the NumPy Library using the following commands:

pip install numpy


In [1]:
#importing numpy
import numpy as np

**Step 2:** Create arrays for three branches, a, b, and c, for four weeks of store sales

In [2]:
#weeks[1,2,3,4]
branch_a = np.array([120,150,190,125])
branch_b = np.array([130,160,280,175])
branch_c = np.array([140,150,250,180])


In [3]:
#created arrays
branch_a, branch_b, branch_c


(array([120, 150, 190, 125]),
 array([130, 160, 280, 175]),
 array([140, 150, 250, 180]))

**Step 3:** Check the properties of the arrays with different attributes


In [4]:
#dimensions of the array
branch_c.ndim

1

In [17]:
#shape of the array 
branch_b.shape


(4,)

In [18]:
#size of the array
branch_a.size

4

In [19]:
#Datatype of the branches
branch_c.dtype

dtype('int32')

In [20]:
#space used by each element in the array
branch_a.itemsize, branch_c.itemsize

(4, 4)

**Step 4:** Retretive Sales data by Indexing & Slicing the arrays


In [21]:
#Index starts with 0
#Get the branch_b week 2 sales data
branch_b[1]

160

In [22]:
#Get the unique values in the branch_b 
np.unique(branch_c)

array([140, 150, 180, 250])

In [23]:
#Get branch_b week 1,2 sales data
branch_a[0:3]

array([120, 150, 190])

In [24]:
#Get branch_c last two weeks sales data
branch_c[2:5]

array([250, 180])

In [25]:
#Get branch_a last three weeks sales data (negitive slicing)
branch_a[-3:]

array([150, 190, 125])

**Step 5:** Assign new values to the branch sales (Broadcasting)


In [26]:
branch_b

array([130, 160, 280, 175])

In [27]:
#Make a new copy for branch_b
branch_b_sunil= branch_b

In [28]:
branch_b_sunil

array([130, 160, 280, 175])

In [29]:
#updating week 1sales data 
branch_b_sunil[0] = 125
branch_b_sunil

array([125, 160, 280, 175])

In [37]:
#Adding week 5,6 sales data to the branch_b_sunil array
branch_b_sunil = np.append(branch_b_sunil,[230,185])

In [38]:
branch_b_sunil

array([125, 160, 280, 175, 300, 170, 230, 185])

In [39]:
# Updating week 5, 6 sales data using slicing
branch_b_sunil[4:6] = [300, 170]
branch_b_sunil


array([125, 160, 280, 175, 300, 170, 230, 185])

**Step 6:** Arithmetic Operations on the sales data

In [40]:
branch_c

array([140, 150, 250, 180])

In [41]:
#Adding +2sales to all 4 weeks data
branch_a + 2

array([122, 152, 192, 127])

In [42]:
#Subtracting 100 sales from the week 4 data with indexing in branch_c
branch_c[3] - 10

170

In [43]:
#Double the sales in week 2 with indexing in branch_c
branch_c[1] * 2

300

In [44]:
#Half sales in week 2 & 3 
branch_c[1:3]  / 2

array([ 75., 125.])

**Step 7:** Statistical Operations on the sales data


In [45]:
branch_a, branch_b, branch_c

(array([120, 150, 190, 125]),
 array([125, 160, 280, 175]),
 array([140, 150, 250, 180]))

In [46]:
#What are the Total sales of brranch_b
np.sum(branch_b)

740

In [47]:
#What are the Max and min sales of the branch_b
np.max(branch_b), np.min(branch_b)

(280, 125)

In [48]:
#What are the average (mean) sales of the each branch 
print(np.mean(branch_b), np.mean(branch_c))

185.0 180.0


**Step 8:** Combine all branches sales data (Concatenating)

In [49]:
#Combaing all 3 branchs sales 
all_branches_sales = np.concatenate([branch_a, branch_b, branch_c])

In [50]:
branch_a.ndim

1

In [51]:
all_branches_sales

array([120, 150, 190, 125, 125, 160, 280, 175, 140, 150, 250, 180])

In [52]:
#Total sales of all branchs
np.sum(all_branches_sales)

2045

**Step 9:** Reshape the all_branches_sales into 3x4 matrix


In [53]:
all_branches_sales.ndim, all_branches_sales.shape


(1, (12,))

In [54]:
all_branches_sales = all_branches_sales.reshape(3,4)
all_branches_sales

array([[120, 150, 190, 125],
       [125, 160, 280, 175],
       [140, 150, 250, 180]])

In [55]:
#Indexing 2-D array
all_branches_sales[0]

array([120, 150, 190, 125])

In [56]:
#sort Row wise sales
np.sort(all_branches_sales, axis=1)

array([[120, 125, 150, 190],
       [125, 160, 175, 280],
       [140, 150, 180, 250]])

In [57]:
# Splitting the all_branches_sales array into 3 different arrays
# Splitting based on rows (axis=0)
split_a, split_b, split_c = np.split(all_branches_sales, [1,2], axis=0)

In [58]:
split_a

array([[120, 150, 190, 125]])

In [59]:
split_b

array([[125, 160, 280, 175]])

In [60]:
# What are the Week 2 sales of all three branches?
# Slice only column 2
week_2_sales = all_branches_sales[:3, 1:2]


In [61]:
print(week_2_sales)

[[150]
 [160]
 [150]]


***RESULT:***
By using the NumPy library, various operations on arrays such as creation, attribute access, indexing, slicing, broadcasting,
arithmetic operations, statistical computations, concatenation, sorting, and splitting were successfully implemented and
demonstrated using store sales data.
